version: "3.8"
services:
  frontend:
    build: ./frontend
    image: yshah20/news-app-frontend
    ports:
      - 8080:8080
  backend:
    build: ./backend
    image: yshah20/news-app-backend
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
  db:
    image: postgres
    ports:
      - 4444:5432
    volumes:
      - ./data_dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ~/.postgres:/var/lib/postrgesql/data
    environment:
      POSTGRES_USER: yash
      POSTGRES_PASSWORD: root
      POSTGRES_DB: news
