version: "3.8"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/home/news-app-frontend
    image: yshah20/news-app-frontend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      backend:
        condition: service_started
  backend:
    build: ./backend
    image: yshah20/news-app-backend
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    restart: always
    volumes:
      - ./backend:/usr/home/news-app
    depends_on:
      db:
        condition: service_started
  db:
    image: postgres
    volumes:
      - ./data_dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - pg-data:/var/lib/postrgesql/data
    environment:
      POSTGRES_USER: yash
      POSTGRES_PASSWORD: root
      POSTGRES_DB: news
volumes:
  pg-data:
